version: "2.0"
services:
  zabbix_db:
    image: mysql:5.7
    networks: 
      - zabbix-net
    volumes:
      - "./db_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: &MYSQL_PASSWORD "123456"
    ports:
      - "32001:3306"
  zabbix_server:
    image: zabbix/zabbix-server-mysql:centos-latest
    networks: 
      - zabbix-net
    restart: always
    environment: 
      DB_SERVER_HOST: "zabbix_db"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
    ports:
      - "32002:10051"
    depends_on:
      - zabbix_db
  zabbix_web:
    image: zabbix/zabbix-web-nginx-mysql:centos-latest
    networks: 
      - zabbix-net
    restart: always
    environment: 
      DB_SERVER_HOST: "zabbix_db"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      ZBX_SERVER_HOST: "zabbix_server"
    ports:
      - "32003:80"
      - "32004:443"
    depends_on:
      - zabbix_db
      - zabbix_server
  ansible:
    image: dreamlongs/ansible
    restart: always
    ports:
      - "32005:443"
    entrypoint: "/entrypoint.sh ansible-tower"
  cobbler:
    image: dreamlongs/cobbler
    network_mode: "host"        
    privileged: true
    #cap_add:
    #  - ALL
    #entrypoint: "/entrypoint.sh ${IPADDRESS}"
    #command: "/entrypoint.sh ${IPADDRESS}"   
  main_web:
    image: dreamlongs/netcore2.2
    restart: always
    ports:
      - "32006:5000"
    volumes:
      - "./publish:/app"
    working_dir: "/app"    
    entrypoint: "dotnet MaintainPlatform.dll"
networks:
  zabbix-net: