version: "2.1"
services:
  zabbix_db:
    image: mysql:5.7
    networks: 
      - maintain-net
    volumes:
      - "./mysql_db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: &MYSQL_PASSWORD "123456"
    ports:
      - "32001:3306"
  zabbix_server:
    image: zabbix/zabbix-server-mysql:centos-latest
    networks: 
      - maintain-net
    restart: always
    environment: 
      DB_SERVER_HOST: "zabbix_db"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
    ports:
      - "32002:10051"
    depends_on:
      - zabbix_db
  zabbix_web:
    image: dreamlongs/zabbix_web
    # zabbix/zabbix-web-nginx-mysql:centos-latest
    networks: 
      - maintain-net
    restart: always
    environment: 
      DB_SERVER_HOST: "zabbix_db"
      MYSQL_USER: "root" 
      MYSQL_PASSWORD: *MYSQL_PASSWORD
      ZBX_SERVER_HOST: "zabbix_server"
    ports:
      - "32003:80"
      - "32004:443"
    volumes:
      - "./favicon.ico:/usr/share/zabbix/favicon.ico" 
    depends_on:
      - zabbix_db
      - zabbix_server
  ansible:
    image: dreamlongs/ansible
    restart: always
    networks: 
      - maintain-net
    volumes:
      - "./favicon.ico:/var/lib/awx/public/static/assets/favicon.ico"
      - "./hosts:/app/wwwroot/hosts"
      - "./zh.json:/var/lib/awx/public/static/languages/zh.json"
      - "./ansible_db:/var/lib/postgresql/9.6/main/base"
    ports:
      - "32005:443"
      - "32006:5432"
    entrypoint: "/entrypoint.sh ansible-tower"
  cobbler:
    image: dreamlongs/cobbler
    network_mode: "host"        
    privileged: true
    entrypoint: "/sbin/init"
    volumes:
      - "./favicon.ico:/var/www/cobbler_webui_content/favicon.ico"
      - "./entrypoint.sh:/entrypoint.sh"
  main_web:
    image: dreamlongs/netcore2.2
    restart: always
    ports:
      - "80:5000"
    networks: 
      - maintain-net
    volumes:
      - "./publish:/app"
    working_dir: "/app"    
    entrypoint: "dotnet MaintainPlatform.dll"
networks:
  maintain-net:
